version: '3.7'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - docker_backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file:
         .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8080:80
    networks:
      - docker_frontend
      - docker_backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_NAME}'
   volumes:
      - ./wordpress:/var/www/html/wordpress
   env_file:
     .env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  docker_frontend:
    driver: overlay
  docker_backend:
    driver: overlay

volumes:
  db_data:
    wordpress:
